lab-brussels-1/HYF-Redesign-Group-3

- planning/communication-plan.md
- planning/user-persona.md
> Maria communication

- planning/communication-plan.md
- planning/user-persona.md
> Maria user personas

- .cspell.json
- planning/constraints.md
> adding constraints file

- package-lock.json
- package.json
- planning/communication-plan.md
> add a communication-plan.md

- planning/user-persona.md
> Add a new user-persona

- planning/backlog.md
> adding draft backlog

- planning/development-strategy.md
> adding draft development strategy

- planning/communication-plan.md
> change my hours in communication plan

- planning/backlog.md
> backlog desc/sentence structure update

- planning/backlog.md
- planning/communication-plan.md
- planning/development-strategy.md
> update planning files desc

- index.html
- styles/something.css
> Zerubabel  add our impact code

- .cspell.json
- .vscode/settings.json
- index.html
- planning/development-strategy.md
- styles/index.css
- styles/something.css
- styles/style.css
> adding support us section

- index.html
> fix problem with responsivity of image

- index.html
- styles/style.css
> Maria header update2

- index.html
- styles/style.css
> Maria update2

- styles/faq.css
> Created faq.html file in Pages folder

- index.html
- styles/style.css
> Zerubabel add our core values code

- index.html
> zerubabel add icon visible correction

- index.html
- styles/style.css
> Enhance Homepage image

- index.html
- pages/about.html
- styles/about.css
> add OUR-MISSION-OUR-VISION-code

- README.md
> fix swapped img

- pages/faq.html
- styles/faq.css
> Footer fixing

- index.html
- styles/faq.css
> Navbar enhancement_issue88

- planning/retrospective.md
> adding retrospective file

- pages/faq.html
> Change the path to faq

- .cspell.json
- pages/about.html
- pages/faq.html
- styles/about.css
> fix the issue with css style in About page

- .cspell.json
- index.html
- pages/about.html
- pages/faq.html
> fix the issue with img
